### ISSUE TITLE
tsinghua.app is currently offline

### ISSUE THREAD

**Issue by YuruiHong** [robertying/tsinghua.app-web#2]
Seems a server issue
![Screenshot 2023-08-08 at 14-11-51 课程信息共享计划 courseX｜星期四 Thursday](https://github.com/robertying/tsinghua.app-web/assets/83064277/c6c49c47-5038-4fd8-9a27-bed3805a0a81)
![Screenshot 2023-08-08 at 14-29-39 tsinghua app 502 Bad gateway](https://github.com/robertying/tsinghua.app-web/assets/83064277/6548bc02-0ec2-4d38-9070-6ac9407c36bd)

**Comment by robertying** [comment]
最近经常这样，之后有机会看看到底啥问题，暂时重启了。
